const ActionTypes = {
    USERNAME: 'USERNAME',
    CURRENTUSER: 'CURRENTUSER',
    ALLUSERS: 'ALLUSERS',
    MESSAGES: 'MESSAGES',
    CHANGERECPUID: 'CHANGERECPUID',
    UPDATEPORTFOLIO: 'UPDATEPORTFOLIO',
    SHOW_MESSAGES: 'SHOW_MESSAGES',
    LOGIN: 'LOGIN'
}

export default ActionTypes;
